### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by AlexandreRousselet** [Vulca/POLAND#12]
+ General 
- [x] Survey Volunteer
- [x] Introduce board
- [x] pdf. Poznan Network
- [x] Change video intro
- [x] Add Pawel, Agata, Jackub
- [x] add email adress seminar@vulca.eu
- [x] revoir le menu (T.S)
- [x] Correction Pawel (T.S)
- [x]  Correction Aleks (T.S)
- [x]  Correction Jakub (T.S)
- [x]  CONTACT US : after submiting change the title "issue" and put "Seminar Request" (T.S)
- [x] Tracking system vulca website (google analytics?) (All)
- [x] Warning and udpate about GRPD (All)
- [x] mauvais lien derrière logo fablab poznan 
add this one: https://drive.google.com/a/program-vulca.eu/file/d/1ZdFJB_i_qs60G82TMjC-DKWkDyC55RaH/view?usp=sharing
- [x]  jakub sentence : “Dad of two young next generation makers”
- [x] corriger color box for Accomodation (T.S)
- [x] Corriger le problème d'envoi de la demande d'accomodation (T.S)

* Com' : 
- [x] Design de lancement (FB,TW,IG,WA) - (A.R)
- [x] Com global retroplanning (A.R)

Logistic 
- [x] Geolocalisation train + Airport (with distance)
- [x] List of accomidation

+
- [x] First proofreading Aleks
- [x] Second proofreading Matthew 
- [x] Last proofreading

_________________________

+ Ticketing & Budget
- [x] Price event
- [x] Date early bird  
- [x] Annoncer les prices à L'équipe pologne (A.R)
- [x] Compte banque à lier à l'éventBrite. (T.S + N.F)
- [x] Système de facturation (N.F)
- [x] Donation button
- [x] Hello Asso (N.F)
- [x] Validate package and price (ALL)
- [x] Design Sponsoring (Alex)
- [x] Be the first (add .pdf sponsors) (T.S)

+ External Link:
- [x] Pawel facebook and not twitter
- [x] Thomas linkeding error 
- [x] External link email

+ Other Pages : 
- [x] Add Thomas Map 
- [x] Home page (nicolas)
- [x] Add Experiences part (5 italy, Slovenie, Germany, Demnark).

**Comment by AlexandreRousselet** [comment]
For @Thomas0sanz - COORDINATION TEAM
https://docs.google.com/spreadsheets/d/1l_jdaLCLdVs7W3JotgmEjbtcUO-tfPhtzCDUn6PRvkY/edit#gid=0

**Comment by AlexandreRousselet** [comment]
For @Thomas0sanz 
- Introducing Polish meeting (corrected by matty)
![introduce---polish-network](https://user-images.githubusercontent.com/45399609/52177681-9c3ba400-27bc-11e9-97e3-34d5061f2258.jpg)

**Comment by nicolasdb** [comment]
Check des liens du site. 
- pas de retour vers cette page de séminaire si l'on click sur ces 3 premiers boutons. Mais pas très grave. 
![image](https://user-images.githubusercontent.com/12049360/52178685-cfd4f900-27d1-11e9-99f1-9cf41f0b8648.png)
- ok, good
![image](https://user-images.githubusercontent.com/12049360/52178703-fd21a700-27d1-11e9-9d36-0ced8bdc7401.png)
- ok pour eventbrite
![image](https://user-images.githubusercontent.com/12049360/52178708-24787400-27d2-11e9-9e8d-393062ad66e9.png)
- le reste ok aussi. 

Puis ceci, ça marche pas. Alors est-ce que c'est important ou pas? Si ça ne marche pas, est-ce qu'on les mets? 
En plus, j'ai pas tweeter et j'ai 10 photos sur mon instagram. du coup, peu d'intérêt à ce que les gens viennent voir ce que j'ai là. 
![image](https://user-images.githubusercontent.com/12049360/52178734-60abd480-27d2-11e9-91f6-bf15541fccad.png)

**Comment by AlexandreRousselet** [comment]
// From 15 feb to 15 March - *Early Bird*
--> Ticket 20€/Day (60€/3 jrs).

// Du 15 Mars au 15 Avril - Normal ticket
--> Ticket 40€/Day (120€ les 3 jrs)

// From 15 April to 31 April
--> Ticketing à 180€ 
(to define better before the openning.).

**Comment by AlexandreRousselet** [comment]
@Thomas0sanz lien vidéo (à voir comment ça rend)
https://youtu.be/zQY3QQW5IYY

**Comment by AlexandreRousselet** [comment]
@Thomas0sanz  design sur lequel tu peux t'inspiré comme demandé. 

![fichier 1 2x-80](https://user-images.githubusercontent.com/45399609/52223673-0bd59000-289e-11e9-9183-6ea34b1e648b.jpg)

**Comment by AlexandreRousselet** [comment]
@Thomas0sanz problème d'affichage des couleurs dans le form d'accomodation 
Ecriture blanche sur fond blanc. 
<img width="593" alt="capture d ecran 2019-02-15 a 10 18 15" src="https://user-images.githubusercontent.com/45399609/52850375-3c71c100-310b-11e9-8268-cdd9b116b5a9.png">

**Comment by Thsanz** [comment]
> @Thomas0sanz problème d'affichage des couleurs dans le form d'accomodation
> Ecriture blanche sur fond blanc.
> De plus je ne peux pas envoyer ma request.
> 
> <img alt="capture d ecran 2019-02-15 a 10 18 15" width="593" src="https://user-images.githubusercontent.com/45399609/52850375-3c71c100-310b-11e9-8268-cdd9b116b5a9.png">

Le problème est reglé.
La raison pour laquelle tu ne pouvais pas envoyé ta requette est que le cadre était rouge, était parce qu'il attendait une adresse e-mail.

**Comment by Thsanz** [comment]
> * General
> 
> * [x]  Survey Volunteer
> * [x]  Introduce board
> * [x]  pdf. Poznan Network
> * [x]  Change video intro
> * [x]  Add Pawel, Agata, Jackub
> * [x]  add email adress [seminar@vulca.eu](mailto:seminar@vulca.eu)
> * [x]  revoir le menu (T.S)
> * [x]  Correction Pawel (T.S)
> * [x]   Correction Aleks (T.S)
> * [x]   Correction Jakub (T.S)
> * [ ]   CONTACT US : after submiting change the title "issue" and put "Seminar Request" (T.S)
> * [x]  Tracking system vulca website (google analytics?) (All)
> * [ ]  Warning and udpate about GRPD (All)
> * [x]  mauvais lien derrière logo fablab poznan
>   add this one: https://drive.google.com/a/program-vulca.eu/file/d/1ZdFJB_i_qs60G82TMjC-DKWkDyC55RaH/view?usp=sharing
> * [x]   jakub sentence : “Dad of two young next generation makers”
> * [ ]  corriger color box for Accomodation (T.S)
> * [ ]  Corriger le problème d'envoi de la demande d'accomodation (T.S)
> 
> * Com' :
> 
> * [x]  Design de lancement (FB,TW,IG,WA) - (A.R)
> * [ ]  Com global retroplanning (A.R)
> 
> Logistic
> 
> * [x]  Geolocalisation train + Airport (with distance)
> * [x]  List of accomidation
> 
> 
> * [x]  First proofreading Aleks
> * [x]  Second proofreading Matthew
> * [x]  Last proofreading
> 
> * Ticketing & Budget
> 
> * [x]  Price event
> * [x]  Date early bird
> * [x]  Annoncer les prices à L'équipe pologne (A.R)
> * [ ]  Compte banque à lier à l'éventBrite. (T.S + N.F)
> * [ ]  Système de facturation (N.F)
> * [ ]  Donation button
> * [x]  Hello Asso (N.F)
> * [x]  Validate package and price (ALL)
> * [ ]  Design Sponsoring (Alex)
> * [ ]  Be the first (add .pdf sponsors) (T.S)
> 
> * External Link:
> 
> * [x]  Pawel facebook and not twitter
> * [x]  Thomas linkeding error
> * [x]  External link email
> 
> * Other Pages :
> 
> * [x]  Add Thomas Map
> * [x]  Home page (nicolas)
> * [ ]  Add Experiences part (5 italy, Slovenie, Germany, Demnark).

"poznan request" done
